# This is a basic workflow to help you get started with Actions

name: ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/mingw-w64.yml'
      - '.github/workflows/macos.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/mingw-w64.yml'
      - '.github/workflows/macos.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # env
    env:
      TERM: xterm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: intall apt packages
      run: sudo apt-get -qq install pkg-config rake bison libtool-bin libncurses5-dev libncursesw5-dev
    # Runs a single command using the runners shell
    - name: build
      run: rake 
    # Runs a set of commands using the runners shell
    - name: test
      run: rake test
